Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -61,17 +61,33 @@ jobs:
         echo "=== Contenido de docs/ ==="
         ls -la docs/
         
-        if [ ! -f "docs/visualizations.png" ]; then
-          echo "::error::El archivo visualizations.png no fue creado"
+        # Verificar si las imágenes se han generado correctamente
+        if [ ! -f "docs/visualization1.png" ]; then
+          echo "::error::El archivo visualization1.png no fue creado"
           exit 1
         fi
         
+        if [ ! -f "docs/visualization2.png" ]; then
+          echo "::error::El archivo visualization2.png no fue creado"
+          exit 1
+        fi
+        
+        if [ ! -f "docs/visualization3.png" ]; then
+          echo "::error::El archivo visualization3.png no fue creado"
+          exit 1
+        fi
+        
+        if [ ! -f "docs/visualization4.png" ]; then
+          echo "::error::El archivo visualization4.png no fue creado"
+          exit 1
+        fi
+        
+        # Verificar si el archivo index.html fue creado
         if [ ! -f "docs/index.html" ]; then
           echo "::error::El archivo index.html no fue creado"
           exit 1
         fi
 
-    
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
